plugins:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Include:
    - lib/**/*.rb
    - test/**/*.rb
  Exclude:
    - 'lib/idnx/ruby.rb'
    - '.bundle/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
